package com.orangehrm.pages;

import org.openqa.selenium.By;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.support.FindBy;

/**
 * AddEmployeePage - Page Object cho form thêm/chỉnh sửa nhân viên
 * URL: /web/index.php/pim/addEmployee
 */
public class AddEmployeePage extends BasePage {

    // ==================== WEB ELEMENTS ====================

    @FindBy(css = "input[placeholder='First Name']")
    private WebElement firstNameField;

    @FindBy(css = "input[placeholder='Middle Name']")
    private WebElement middleNameField;

    @FindBy(css = "input[placeholder='Last Name']")
    private WebElement lastNameField;

    @FindBy(xpath = "//label[contains(text(),'Employee Id')]/following::input[1]")
    private WebElement employeeIdField;

    @FindBy(css = "button[type='submit'].oxd-button--secondary")
    private WebElement saveButton;

    @FindBy(css = "button[type='button'].oxd-button--ghost")
    private WebElement cancelButton;

    @FindBy(css = ".employee-image-wrapper")
    private WebElement profilePhotoSection;

    // Toggle tạo tài khoản login
    @FindBy(css = ".oxd-switch-input")
    private WebElement createLoginDetailsToggle;

    @FindBy(css = "input[autocomplete='username']")
    private WebElement newUsernameField;

    @FindBy(css = "input[type='password']:nth-of-type(1)")
    private WebElement newPasswordField;

    @FindBy(css = "input[type='password']:nth-of-type(2)")
    private WebElement confirmPasswordField;

    // Toast message
    @FindBy(css = ".oxd-toast-content-text")
    private WebElement toastMessage;

    // ==================== PAGE ACTIONS ====================

    /**
     * Điền thông tin cơ bản nhân viên
     */
    public AddEmployeePage fillBasicInfo(String firstName, String middleName, String lastName) {
        type(firstNameField, firstName);
        if (middleName != null && !middleName.isEmpty()) {
            type(middleNameField, middleName);
        }
        type(lastNameField, lastName);
        logger.info("📝 Điền thông tin: {} {} {}", firstName, middleName, lastName);
        return this;
    }

    /**
     * Đặt Employee ID tùy chỉnh
     */
    public AddEmployeePage setEmployeeId(String employeeId) {
        clearAndType(employeeIdField, employeeId);
        logger.info("🆔 Đặt Employee ID: {}", employeeId);
        return this;
    }

    /**
     * Lấy Employee ID được tạo tự động
     */
    public String getAutoGeneratedEmployeeId() {
        return getAttribute(employeeIdField, "value");
    }

    /**
     * Bật/tắt tạo tài khoản đăng nhập
     */
    public AddEmployeePage toggleCreateLoginDetails(boolean enable) {
        boolean isActive = createLoginDetailsToggle.getAttribute("class").contains("--active");
        if (enable != isActive) {
            click(createLoginDetailsToggle);
            logger.info("🔑 Toggle tạo tài khoản: {}", enable ? "BẬT" : "TẮT");
        }
        return this;
    }

    /**
     * Điền thông tin tài khoản đăng nhập cho nhân viên
     */
    public AddEmployeePage fillLoginDetails(String username, String password) {
        try {
            type(newUsernameField, username);
            type(newPasswordField, password);
            type(confirmPasswordField, password);
            logger.info("🔐 Điền thông tin tài khoản: {}", username);
        } catch (Exception e) {
            logger.warn("⚠️ Không tìm thấy form tạo tài khoản - cần bật toggle trước");
        }
        return this;
    }

    /**
     * Lưu thông tin nhân viên
     */
    public EmployeeListPage clickSave() {
        click(saveButton);
        waitForLoadingSpinner();
        logger.info("💾 Đã lưu thông tin nhân viên");
        return new EmployeeListPage();
    }

    /**
     * Hủy thao tác
     */
    public EmployeeListPage clickCancel() {
        click(cancelButton);
        logger.info("❌ Hủy thêm nhân viên");
        return new EmployeeListPage();
    }

    /**
     * Thêm nhân viên hoàn chỉnh (thao tác nhanh)
     */
    public EmployeeListPage addEmployee(String firstName, String lastName) {
        fillBasicInfo(firstName, "", lastName);
        return clickSave();
    }

    // ==================== VERIFICATIONS ====================

    public boolean isAddEmployeePageDisplayed() {
        return getCurrentUrl().contains("addEmployee") || getCurrentUrl().contains("pim");
    }

    public String getFirstName() {
        return getAttribute(firstNameField, "value");
    }

    public String getLastName() {
        return getAttribute(lastNameField, "value");
    }

    public boolean isToastMessageDisplayed() {
        try {
            waitForVisible(toastMessage);
            return true;
        } catch (Exception e) {
            return false;
        }
    }

    public String getToastMessage() {
        waitForVisible(toastMessage);
        return getText(toastMessage);
    }

    public boolean isRequiredFieldErrorDisplayed() {
        By errorSpan = By.cssSelector(".oxd-input-field-error-message");
        try {
            return !driver.findElements(errorSpan).isEmpty();
        } catch (Exception e) {
            return false;
        }
    }
}
